columns:
  age: int64
  workclass: object
  fnlwgt: int64 
  education_num: int64 
  marital_status: object
  occupation: object
  relationship: object
  race: object
  sex: object
  capital_gain: int64 
  capital_loss: int64 
  hours_per_week: int64 
  native_country: object
  wages: object
categorical_columns:
- workclass
- marital_status
- occupation
- relationship
- native_country
- race
- sex
numerical_columns:
- age
- fnlwgt
- education_num
- capital_gain
- capital_loss
- hours_per_week
target_column: wages